sudo: required
services:
  - docker
script:
  - docker build --target builder -t letsencrypt-inwx-builder .
before_deploy:
  - mkdir deploy
  - docker create --name letsencrypt-inwx-builder-container letsencrypt-inwx-builder
  - docker cp letsencrypt-inwx-builder-container:/home/rust/src/target/x86_64-unknown-linux-musl/release/letsencrypt-inwx deploy/
  - docker cp letsencrypt-inwx-builder-container:/home/rust/src/target/x86_64-unknown-linux-musl/debian deploy/
  - mv deploy/debian/*.deb deploy/
  - rm -rf deploy/debian
deploy:
  provider: releases
  api_key:
    secure: wBWst3ZAaTkTli+9zxdyiursyVkhLbZ9/cuY4FmRzG55k05L7nwJrfdcEgUpDAtAm41oVqzHec7+bmjJ9MVFpMgeNO8ORwEuLA5wxW6qAOlx9nVn7XqKa8OkaBQxszslPFWlhncfn4qYi33eHq/E82Hxl42QZOy7f+mSoQQeXeaXJ/02CQxtwLXR4yxBtTn4auEL2NN89GRLqpW32OPLJZe+NSS4VBMBOfe5MNFUgLNyr1AKlOfcYvk+4nKBHF8dkhpNObOWCU1OmFauPnaeKwQkJOaZ3QiCrpwUmqLaMlZceKE1TVVrRA3IUqlN1KjSLO+mtNVBeka9Z/NnF8YQR49OENI3PY2t2xRvLYXeJN/NVO9EYKemf8GiBvnf9u4beLxpYaEc/d8LjvXLvMq1yY7XZO+NngJadGmcqIYujYo20vRbIzmj4RPXo2gJaDADIraoNPZWzdbsdnoAPgnmmj8jHzCgup9VPkeIaD073BOPSykxFL2V2QRz2R9E7f6UDHmWOYRQvKwVu+rlN3Q6tDPL3m6W6iMrvhQ67YlIEDqd8gIvo1m7OzLfdRG4GhPuTTZXp8YI7ch271LOjTOokLuUVKU2eUe2J6oh85eDGFEBBiRrNvqp8xKBjSRRSjYI9+0SX7mZXDo8KXa9TkqI/wfnqeFmAfAjNzupbu9tFTs=
  file_glob: true
  file:
    - deploy/*
  skip_cleanup: true
  on:
    tags: true
